### ISSUE TITLE
How to redirect properly from one port to other

### ISSUE THREAD

**Issue by Alexvianet** [cloudfoundry-incubator/haproxy-boshrelease#102]
I have:
```
      properties:
        ha_proxy:
          disable_http: true
          tcp:
            - name: service
              port: 8200
              backend_servers: &ips ((grab conf.service.static_ips))
              backend_port: 8200
            - name: service-ui
              port: 443
              backend_servers: &ips ((grab conf.service.static_ips))
              backend_port: 8200
```

how to configure redirect from 
80 port to 443 and do not rewrite 8200 port
